// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clswcdnpktspnlfehmni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsc3djZG5wa3RzcG5sZmVobW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTkyMzQsImV4cCI6MjA3NDEzNTIzNH0.FSSjvobmd9y-k4fQLZ8U4nkBQQrcIlgZ974qKcQL2pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});